### PR TITLE
dashboard, vault and side-wrapper height fixed #93

### LINKED ISSUE #93: Dashboard height exceeds content
Check `src/pages/Home.tsx` and relevant associated files to determine which content or css element is causing the Dashboard page.

### PR DESCRIPTION
**Pull request by tarnveerSingh**
dashboard, vault and side-wrapper height fixed #93 and here, the side wrapper refer to changes to side bar height extended as well just a bit. #93 resolved

### CODE REVIEW

**Review by rayraspberry — APPROVED** [review]

**Comment by rayraspberry** [comment]
@tarnveerSingh please update your fork and resubmit after conflicts are resolved.

**Comment by rayraspberry** [comment]
also checkout https://app.dework.xyz/y-foundry-dao for additional development bounties

**Comment by tarnveerSingh** [comment]
@rayraspberry, I've fixed the issues. Are you able to merge it now.?

**Comment by rayraspberry** [comment]
there are still conflicts in the css.  please resolve conflicts

**Comment by tarnveerSingh** [comment]
@rayraspberry Sure thing, I'll get it done but can you please tell me where and how many conflicts are there that needs to resolved. Is it just these files - 

src/assets/styles/scss/app.module.scss
src/assets/styles/scss/appcard.module.scss
src/assets/styles/scss/content.module.scss
src/assets/styles/scss/footer.module.scss

..??

Or any other file that needs to be fixed.? Can you please mention the all file name that needs to resolved.?

**Comment by rayraspberry** [comment]
yes it looks like those files

```This branch has conflicts that must be resolved
 to resolve conflicts before continuing.
Conflicting files
src/assets/styles/scss/app.module.scss
src/assets/styles/scss/appcard.module.scss
src/assets/styles/scss/content.module.scss
src/assets/styles/scss/footer.module.scss```

**Pull request closed without merging**
